### ISSUE TITLE
warm macro occurrences cache fails

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/refactor-nrepl#148]
```

[19:37:45.500] ERROR clojure.tools.nrepl.server - Unhandled REPL handler exception processing message {:op warm-macro-occurrences-cache, :prefix-rewriting false, :debug true, :session 42bdc778-c015-4ade-8583-12447be6239b, :id 12}
java.lang.Exception: No namespace: cheshire.core found
	at clojure.core$the_ns.invoke(core.clj:4008)
	at clojure.core$ns_publics.invoke(core.clj:4040)
	at refactor_nrepl.find.find_macros$find_used_macros.invoke(find_macros.clj:239)
	at refactor_nrepl.find.find_macros$warm_macro_occurrences_cache.invoke(find_macros.clj:255)
	at refactor_nrepl.middleware$warm_macro_occurrences_cache_reply.invoke(middleware.clj:91)
	at refactor_nrepl.middleware$wrap_refactor$fn__12205.invoke(middleware.clj:135)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at cider.nrepl.middleware.macroexpand$wrap_macroexpand$fn__18558.invoke(macroexpand.clj:220)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at user$eval19522$fn__19523$fn__19525.invoke(form-init4228459513354274401.clj:1)
	at cider.nrepl.middleware.enlighten$wrap_enlighten$fn__15601.invoke(enlighten.clj:86)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at cider.nrepl.middleware.complete$wrap_complete$fn__13522.invoke(complete.clj:57)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at clojure.tools.nrepl.middleware.pr_values$pr_values$fn__900.invoke(pr_values.clj:22)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at cider.nrepl.middleware.test$wrap_test$fn__18959.invoke(test.clj:286)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
	at cider.nrepl.middleware.pprint$wrap_pprint_fn$fn__15224.invoke(pprint.clj:53)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__717.invoke(middleware.clj:22)
```

**Comment by expez** [comment]
This might be entirely reasonable, though.  And there's absolutely nothing to go on here :p

**Comment by benedekfazekas** [comment]
ha fair point. should be able to reproduce. was like a quick note to myself really. cheshire is in the project file btw and `cheshire.core` should be available
