### ISSUE TITLE
CPU 100% on cider-jack-in

### ISSUE THREAD

**Issue by sunng87** [clojure-emacs/refactor-nrepl#149]
I'm getting a core 100% when running cider-jack-in in one of my project. After checking the thread id, I found it's a refactor_nrepl thread. And here are two thread dump I caught:

```
"clojure-agent-send-off-pool-3" #28 prio=5 os_prio=0 tid=0x00007fcaa0003000 nid=0x631d runnable [0x00007fca9a8fb000]
   java.lang.Thread.State: RUNNABLE
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.node.protocols$eval40195$fn__40250$G__40205__40252.invoke(protocols.clj:9)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.node.protocols$eval40195$fn__40250$G__40204__40255.invoke(protocols.clj:9)
        at clojure.core$map$fn__4553.invoke(core.clj:2624)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        - eliminated <0x00000000fd731a90> (a clojure.lang.LazySeq)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        - locked <0x00000000fd731a90> (a clojure.lang.LazySeq)
        at clojure.lang.RT.seq(RT.java:507)
        at clojure.core$seq__4128.invoke(core.clj:137)
        at clojure.core.protocols$seq_reduce.invoke(protocols.clj:26)
        at clojure.core.protocols$fn__6506.invoke(protocols.clj:100)
        at clojure.core.protocols$fn__6452$G__6447__6465.invoke(protocols.clj:13)
        at clojure.core$reduce.invoke(core.clj:6515)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.node.protocols$concat_strings.invoke(protocols.clj:47)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.node.seq.SeqNode.string(seq.clj:20)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.base$string.invoke(base.clj:75)
        at refactor_nrepl.s_expressions$get_next_sexp$fn__42237.invoke(s_expressions.clj:17)
        at clojure.core$some.invoke(core.clj:2570)
        at refactor_nrepl.s_expressions$get_next_sexp.invoke(s_expressions.clj:16)
        at refactor_nrepl.core$extract_ns_meta.invoke(core.clj:222)
        at refactor_nrepl.core$read_ns_form.invoke(core.clj:242)
        at refactor_nrepl.find.find_macros$collect_occurrences.invoke(find_macros.clj:179)
        at clojure.core$partial$fn__4531.invoke(core.clj:2507)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.walk$postwalk_subtree.invoke(walk.clj:34)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.walk$postwalk_subtree.invoke(walk.clj:32)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.walk$postwalk_subtree.invoke(walk.clj:32)

```

After a while : 
```
"clojure-agent-send-off-pool-3" #28 prio=5 os_prio=0 tid=0x00007fcaa0003000 nid=0x631e runnable [0x00007fca9a8fb000]
   java.lang.Thread.State: RUNNABLE
        at clojure.lang.Util.hasheq(Util.java:173)
        at clojure.lang.PersistentHashMap.hash(PersistentHashMap.java:120)
        at clojure.lang.PersistentHashMap.containsKey(PersistentHashMap.java:126)
        at clojure.lang.APersistentSet.contains(APersistentSet.java:34)
        at clojure.lang.RT.contains(RT.java:787)
        at clojure.core$contains_QMARK_.invoke(core.clj:1421)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.reader$linebreak_QMARK_.invoke(reader.clj:39)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.reader$read_while.doInvoke(reader.clj:62)
        at clojure.lang.RestFn.invoke(RestFn.java:425)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.parser.whitespace$parse_whitespace.invoke(whitespace.clj:12)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.parser.core$eval41523$fn__41524.invoke(core.clj:84)
        at clojure.lang.MultiFn.invoke(MultiFn.java:229)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.reader$read_with_meta.invoke(reader.clj:122)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.parser.core$parse_next.invoke(core.clj:34)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.parser$parse.invoke(parser.clj:13)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.parser$parse_all$fn__41581.invoke(parser.clj:18)
        at clojure.core$repeatedly$fn__5111.invoke(core.clj:4921)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        - eliminated <0x00000000fb035da8> (a clojure.lang.LazySeq)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        - locked <0x00000000fb035da8> (a clojure.lang.LazySeq)
        at clojure.lang.RT.seq(RT.java:507)
        at clojure.core$seq__4128.invoke(core.clj:137)
        at clojure.core$take_while$fn__4604.invoke(core.clj:2774)
        at clojure.lang.LazySeq.sval(LazySeq.java:40)
        - eliminated <0x00000000fb035e00> (a clojure.lang.LazySeq)
        at clojure.lang.LazySeq.seq(LazySeq.java:49)
        - locked <0x00000000fb035e00> (a clojure.lang.LazySeq)
        at clojure.lang.Cons.next(Cons.java:39)
        at clojure.lang.RT.next(RT.java:674)
        at clojure.core$next__4112.invoke(core.clj:64)
        at clojure.core$dorun.invoke(core.clj:3010)
        at clojure.core$doall.invoke(core.clj:3025)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.parser$parse_all.invoke(parser.clj:20)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.parser$parse_string_all.invoke(parser.clj:35)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.base$of_string.invoke(base.clj:63)
        at refactor_nrepl.s_expressions$get_next_sexp.invoke(s_expressions.clj:15)
        at refactor_nrepl.core$extract_ns_meta.invoke(core.clj:222)
        at refactor_nrepl.core$read_ns_form.invoke(core.clj:242)
        at refactor_nrepl.find.find_macros$collect_occurrences.invoke(find_macros.clj:179)
        at clojure.core$partial$fn__4531.invoke(core.clj:2507)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.walk$postwalk_subtree.invoke(walk.clj:34)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.walk$postwalk_subtree.invoke(walk.clj:32)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.walk$postwalk_subtree.invoke(walk.clj:32)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.walk$postwalk_subtree.invoke(walk.clj:32)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.walk$postwalk_subtree.invoke(walk.clj:32)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.walk$postwalk_subtree.invoke(walk.clj:32)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.walk$postwalk_subtree.invoke(walk.clj:32)
        at mranderson047.rewrite_clj.v0v4v13_20150917v134033_1.rewrite_clj.zip.walk$postwalk_subtree.invoke(walk.clj:32)
```

I hope this is useful to you. Please let me know if you need further information. Thanks!

**Comment by sunng87** [comment]
By the way I'm running the latest cider 0.11 from melpa and all these middlewares were automatically injected.

**Comment by expez** [comment]
This is normal.  When the repl starts up we have work to do.  There are several caches to populate.  Artifacts on clojars and maven are cache,  ASTs are prebuilt and cached, macro-definitions in the project are cached.  There might be more too, this is just off the top of my head.

If you don't want to pre-populate the caches you can turn that off.  `M-x customize-group RET> cljr <RET>` to inspect all the available settings.

**Comment by benedekfazekas** [comment]
Thanks for the report. This is expected behaviour if it stops after a while. pls do shout tho if it does not seem to stop after a while

**Comment by sunng87** [comment]
Thanks for your kind reply! I just disabled those three cache option then it's normal now.

I'm not sure if this is an issue but it takes too long to cache (at least 10 minutes) in my largest project. I will keep you notified if I get something valuable.

**Comment by sp3ctum** [comment]
How is the performance for you when you disabled the cache in your large
project?

2016-03-01 5:02 GMT+02:00 Ning Sun <notifications@github.com>:

**Comment by sunng87** [comment]
@sp3ctum Did you mean the performance of refactoring? I didn't test ...
But for normal cider operations, it works great.

**Comment by sp3ctum** [comment]
That's great. I meant both the startup and "showtime" performance.
