### ISSUE TITLE
Get a new snapshot out

### ISSUE THREAD

**Issue by expez** [clojure-emacs/refactor-nrepl#229]
I just tried to get a new snapshot out.

@benedekfazekas @bbatsov Any idea what this is?

```
$ ./build.sh deploy clojars
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.ClassCastException: Cannot cast org.apache.maven.repository.internal.DefaultVersionResolver to org.eclipse.aether.impl.VersionResolver
 at java.lang.Class.cast (Class.java:3369)
    org.eclipse.aether.impl.DefaultServiceLocator$Entry.newInstance (DefaultServiceLocator.java:177)
    org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstances (DefaultServiceLocator.java:150)
    org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstance (DefaultServiceLocator.java:136)
    org.eclipse.aether.impl.DefaultServiceLocator.getService (DefaultServiceLocator.java:300)
    org.eclipse.aether.internal.impl.DefaultRepositorySystem.initService (DefaultRepositorySystem.java:148)
    org.eclipse.aether.impl.DefaultServiceLocator$Entry.newInstance (DefaultServiceLocator.java:180)
    org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstances (DefaultServiceLocator.java:150)
    org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstance (DefaultServiceLocator.java:136)
    org.eclipse.aether.impl.DefaultServiceLocator.getService (DefaultServiceLocator.java:300)
    mranderson048.pomegranate.v0v4v0.cemerick.pomegranate.aether$repository_system.invokeStatic (aether.clj:117)
    mranderson048.pomegranate.v0v4v0.cemerick.pomegranate.aether$repository_system.invoke (aether.clj:112)
    mranderson048.pomegranate.v0v4v0.cemerick.pomegranate.aether$resolve_dependencies_STAR_.invokeStatic (aether.clj:783)
    mranderson048.pomegranate.v0v4v0.cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke (aether.clj:707)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$apply.invoke (core.clj:641)
    mranderson048.pomegranate.v0v4v0.cemerick.pomegranate.aether$resolve_dependencies.invokeStatic (aether.clj:815)
    mranderson048.pomegranate.v0v4v0.cemerick.pomegranate.aether$resolve_dependencies.doInvoke (aether.clj:809)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    leiningen.source_deps$source_deps$fn__2276.invoke (source_deps.clj:296)
    clojure.core$map$fn__4785.invoke (core.clj:2646)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:521)
    clojure.core$seq__4357.invokeStatic (core.clj:137)
    clojure.core$map$fn__4785.invoke (core.clj:2637)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:521)
    clojure.core$seq__4357.invokeStatic (core.clj:137)
    clojure.core$map$fn__4785.invoke (core.clj:2637)
    clojure.lang.LazySeq.sval (LazySeq.java:40)
    clojure.lang.LazySeq.seq (LazySeq.java:49)
    clojure.lang.RT.seq (RT.java:521)
    clojure.core$seq__4357.invokeStatic (core.clj:137)
    clojure.core$dorun.invokeStatic (core.clj:3024)
    clojure.core$doall.invokeStatic (core.clj:3039)
    clojure.walk$walk.invokeStatic (walk.clj:46)
    clojure.walk$postwalk.invokeStatic (walk.clj:52)
    clojure.walk$postwalk.invoke (walk.clj:52)
    leiningen.source_deps$dep_frequency.invokeStatic (source_deps.clj:220)
    leiningen.source_deps$dep_frequency.invoke (source_deps.clj:212)
    leiningen.source_deps$source_deps.invokeStatic (source_deps.clj:296)
    leiningen.source_deps$source_deps.doInvoke (source_deps.clj:285)
    clojure.lang.RestFn.invoke (RestFn.java:439)
    clojure.lang.Var.invoke (Var.java:388)
    clojure.lang.AFn.applyToHelper (AFn.java:160)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__6099.doInvoke (main.clj:272)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:322)
    leiningen.core.main$apply_task.invoke (main.clj:308)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
    leiningen.do$do.invokeStatic (do.clj:40)
    leiningen.do$do.doInvoke (do.clj:32)
    clojure.lang.RestFn.invoke (RestFn.java:486)
    clojure.lang.Var.invoke (Var.java:401)
    clojure.lang.AFn.applyToHelper (AFn.java:171)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__6099.doInvoke (main.clj:272)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:322)
    leiningen.core.main$apply_task.invoke (main.clj:308)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
    leiningen.core.main$_main$fn__6165.invoke (main.clj:401)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:482)
    clojure.lang.Var.invoke (Var.java:401)
    clojure.lang.AFn.applyToHelper (AFn.java:171)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:551)
    clojure.lang.Var.invoke (Var.java:419)
    clojure.lang.AFn.applyToHelper (AFn.java:186)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```

**Comment by benedekfazekas** [comment]
does not ring a bell at a quick look :/

**Comment by bbatsov** [comment]
Same here. Seems that inlining `pomegranate` broke it somehow. I see it's calling out to some non-inlined deps, which reminds of this Mr Anderson problem https://github.com/benedekfazekas/mranderson/issues/7

**Comment by bbatsov** [comment]
@expez Won't this be solved by my suggestion to drop `alembic` and the hot-loading functionality for now?

**Comment by expez** [comment]
@bbatsov No, that had no effect, unfortunately :(

I tried build after removing every mention of `alembic` from the project.  The classpath conflict must arise elsewhere.

**Comment by mgerlach-klick** [comment]
On the master branch (9e1952c435841b2a9d263e), running `./build.sh deploy clojars` (after changing the project.clj group-id to my own) does not throw an exception using JVM version 1.8.0_51 and does in fact deploy a snapshot (https://clojars.org/org.clojars.phyrex/refactor-nrepl).

Is this not in master, or am I missing something else?

**Comment by mgerlach-klick** [comment]
@expez any idea?

**Comment by birdspider** [comment]
I don't know if related but I get a ClassNotFoundException building master:9e1952c  with `./build.sh` , but I'm using java10

```
~ $ java -version
openjdk version "10.0.1" 2018-04-17
OpenJDK Runtime Environment (build 10.0.1+10)
OpenJDK 64-Bit Server VM (build 10.0.1+10, mixed mode)
```

```
...
Retrieving net/cgrand/parsley/0.9.1/parsley-0.9.1.jar from clojars
Retrieving ordered/ordered/1.3.2/ordered-1.3.2.jar from clojars
Compiling 2 source files to /home/<user>/Projekte/repos/cloned/refactor-nrepl/target/classes
warning: Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '10'
1 warning
Reflection warning, mranderson048/alembic/v0v3v2/dynapath/v0v2v3/dynapath/defaults.clj:13:52 - reference to field getURLs can't be resolved.
Reflection warning, mranderson048/alembic/v0v3v2/dynapath/v0v2v3/dynapath/defaults.clj:27:28 - call to method addURL can't be resolved (target class is unknown).
Exception in thread "main" java.lang.ClassNotFoundException: sun.misc.Launcher, compiling:(mranderson048/alembic/v0v3v2/dynapath/v0v2v3/dynapath/defaults.clj:29:3)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6730)
        at clojure.lang.Compiler.analyze(Compiler.java:6524)
        at clojure.lang.Compiler.analyze(Compiler.java:6485)
        at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
        at clojure.lang.Compiler$LetExpr$Parser.parse(Compiler.java:6179)
        at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
        at clojure.lang.Compiler.analyze(Compiler.java:6524)
        at clojure.lang.Compiler.analyze(Compiler.java:6485)
...
Caused by: java.lang.ClassNotFoundException: sun.misc.Launcher
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
```

**Comment by mgerlach-klick** [comment]
@birdspider sun.misc.launcher is one of the namespaces that got removed/changed with java 9. There are a bunch of references about this error here https://github.com/technomancy/leiningen/issues/2149 and in this project e.g. #206. I'm not sure why you're getting that error (but I haven't read the threads in detail) but it's probably something else than @expez 's issue

**Comment by expez** [comment]
> Is this not in master, or am I missing something else?

That fails for both me and @bbatsov.  I have another version of java, though:

```
$ java -version
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)

```

**Comment by mgerlach-klick** [comment]
```sh
java -version                                                         
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)
```
which is the latest java8 offered through homebrew on macos (10.13.5)

**Comment by mgerlach-klick** [comment]
I installed an ubuntu VM and I tried it there:
```sh
osboxes@osboxes:~/Desktop/refactor-nrepl$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.17.10.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```

Interesting this fails a test, but
```sh
lein do clean, source-deps :prefix-exclusions "[\"classlojure\"]"
lein with-profile plugin.mranderson/config install
```

works and installs the jar locally without any ClassCastException shenanigans. I even tried deploying to clojars again, which also worked.
This is on Ubuntu 17.10, Leiningen 2.8.1 on Java 1.8.0_171 OpenJDK 64-Bit Server VM.

@expez can you maybe try it on a different or virtual machine that doesn't have old baggage around?

**Comment by mbuczko** [comment]
I'm also able to generate snapshot with no errors (on newly cloned repo).

```
$ java -version
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**Comment by expez** [comment]
```
$ java -version                                                                                                                               (100)
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```
```
$ lein do clean, source-deps :prefix-exclusions "[\"classlojure\"]"

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.ClassCastException: Cannot cast org.apache.maven.repository.internal.DefaultVersionResolver to org.eclipse.aether.impl.VersionResolver
 at java.lang.Class.cast (Class.java:3369)
    org.eclipse.aether.impl.DefaultServiceLocator$Entry.newInstance (DefaultServiceLocator.java:177)
    org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstances (DefaultServiceLocator.java:150)
    org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstance (DefaultServiceLocator.java:136)
    org.eclipse.aether.impl.DefaultServiceLocator.getService (DefaultServiceLocator.java:300)
    org.eclipse.aether.internal.impl.DefaultRepositorySystem.initService (DefaultRepositorySystem.java:148)
    org.eclipse.aether.impl.DefaultServiceLocator$Entry.newInstance (DefaultServiceLocator.java:180)
    org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstances (DefaultServiceLocator.java:150)
    org.eclipse.aether.impl.DefaultServiceLocator$Entry.getInstance (DefaultServiceLocator.java:136)
    org.eclipse.aether.impl.DefaultServiceLocator.getService (DefaultServiceLocator.java:300)
    mranderson048.pomegranate.v0v4v0.cemerick.pomegranate.aether$repository_system.invokeStatic (aether.clj:117)
    mranderson048.pomegranate.v0v4v0.cemerick.pomegranate.aether$repository_system.invoke (aether.clj:112)
    mranderson048.pomegranate.v0v4v0.cemerick.pomegranate.aether$resolve_dependencies_STAR_.invokeStatic (aether.clj:783)
    mranderson048.pomegranate.v0v4v0.cemerick.pomegranate.aether$resolve_dependencies_STAR_.doInvoke (aether.clj:707)
```

sigh

Guess we've definitively narrowed it down to a classpath conflict at least.

**Comment by mgerlach-klick** [comment]
So weird.
What leiningen version are you on? I'm on 2.8.1. on macos and ubuntu both.

**Comment by mgerlach-klick** [comment]
In case this helps any
```sh
/tmp/refactor-nrepl(master*)❯ lein deps :tree                                                             
Possibly confusing dependencies found:
[org.clojure/tools.namespace "0.3.0-alpha3"]
 overrides
[cider/orchard "0.3.0"] -> [org.clojure/tools.namespace "0.3.0-alpha4" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[cider/orchard "0.3.0" :exclusions [org.clojure/tools.namespace]]

[org.clojure/clojure "1.7.0"]
 overrides
[leiningen-core "2.7.1"] -> [org.clojure/clojure "1.8.0"]
 and
[org.clojure/clojurescript "1.9.89"] -> [org.clojure/clojure "1.8.0"]

Consider using these exclusions:
[leiningen-core "2.7.1" :exclusions [org.clojure/clojure]]
[org.clojure/clojurescript "1.9.89" :exclusions [org.clojure/clojure]]

[alembic "0.3.2"] -> [org.tcrawley/dynapath "0.2.3" :exclusions [org.clojure/clojure]]
 overrides
[leiningen-core "2.7.1"] -> [org.tcrawley/dynapath "0.2.4"]
 and
[cider/cider-nrepl "0.14.0"] -> [org.tcrawley/dynapath "0.2.4" :exclusions [org.clojure/clojure]]
 and
[cider/orchard "0.3.0"] -> [org.tcrawley/dynapath "0.2.5" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[leiningen-core "2.7.1" :exclusions [org.tcrawley/dynapath]]
[cider/cider-nrepl "0.14.0" :exclusions [org.tcrawley/dynapath]]
[cider/orchard "0.3.0" :exclusions [org.tcrawley/dynapath]]

[org.clojure/tools.namespace "0.3.0-alpha3"] -> [org.clojure/java.classpath "0.2.3"]
 overrides
[cider/orchard "0.3.0"] -> [org.clojure/java.classpath "0.3.0" :exclusions [org.clojure/clojure]]

Consider using these exclusions:
[cider/orchard "0.3.0" :exclusions [org.clojure/java.classpath]]

[leiningen-core "2.7.1"] -> [com.cemerick/pomegranate "0.3.1" :exclusions [org.tcrawley/dynapath]] -> [org.apache.maven.wagon/wagon-provider-api "2.2"]
 overrides
[leiningen-core "2.7.1"] -> [org.apache.maven.wagon/wagon-http "2.10"] -> [org.apache.maven.wagon/wagon-http-shared "2.10"] -> [org.apache.maven.wagon/wagon-provider-api "2.10"]
 and
[leiningen-core "2.7.1"] -> [org.apache.maven.wagon/wagon-http "2.10"] -> [org.apache.maven.wagon/wagon-provider-api "2.10"]

Consider using these exclusions:
[leiningen-core "2.7.1" :exclusions [org.apache.maven.wagon/wagon-provider-api]]

[leiningen-core "2.7.1"] -> [com.cemerick/pomegranate "0.3.1" :exclusions [org.tcrawley/dynapath]] -> [org.apache.maven/maven-aether-provider "3.0.4"] -> [org.codehaus.plexus/plexus-utils "2.0.6"]
 overrides
[leiningen-core "2.7.1"] -> [pedantic "0.2.0"] -> [com.cemerick/pomegranate "0.2.0"] -> [org.apache.maven.wagon/wagon-http "2.2"] -> [org.apache.maven.wagon/wagon-http-shared4 "2.2"] -> [org.apache.maven.wagon/wagon-provider-api "2.2"] -> [org.codehaus.plexus/plexus-utils "3.0"]
 and
[leiningen-core "2.7.1"] -> [pedantic "0.2.0"] -> [com.cemerick/pomegranate "0.2.0"] -> [org.apache.maven.wagon/wagon-http "2.2"] -> [org.apache.maven.wagon/wagon-provider-api "2.2"] -> [org.codehaus.plexus/plexus-utils "3.0"]
 and
[leiningen-core "2.7.1"] -> [pedantic "0.2.0"] -> [com.cemerick/pomegranate "0.2.0"] -> [org.sonatype.aether/aether-connector-wagon "1.13.1"] -> [org.sonatype.sisu/sisu-inject-plexus "2.2.3"] -> [org.codehaus.plexus/plexus-utils "2.0.7"]
 and
[leiningen-core "2.7.1"] -> [com.cemerick/pomegranate "0.3.1" :exclusions [org.tcrawley/dynapath]] -> [org.apache.maven.wagon/wagon-http "2.2"] -> [org.apache.maven.wagon/wagon-http-shared4 "2.2"] -> [org.apache.maven.wagon/wagon-provider-api "2.2"] -> [org.codehaus.plexus/plexus-utils "3.0"]
 and
[leiningen-core "2.7.1"] -> [pedantic "0.2.0"] -> [com.cemerick/pomegranate "0.2.0"] -> [org.apache.maven.wagon/wagon-provider-api "2.2"] -> [org.codehaus.plexus/plexus-utils "3.0"]
 and
[leiningen-core "2.7.1"] -> [pedantic "0.2.0"] -> [com.cemerick/pomegranate "0.2.0"] -> [org.sonatype.aether/aether-connector-wagon "1.13.1"] -> [org.codehaus.plexus/plexus-utils "2.0.7"]
 and
[leiningen-core "2.7.1"] -> [org.apache.maven.wagon/wagon-http "2.10"] -> [org.apache.maven.wagon/wagon-http-shared "2.10"] -> [org.apache.maven.wagon/wagon-provider-api "2.10"] -> [org.codehaus.plexus/plexus-utils "3.0.15"]
 and
[leiningen-core "2.7.1"] -> [com.cemerick/pomegranate "0.3.1" :exclusions [org.tcrawley/dynapath]] -> [org.apache.maven.wagon/wagon-http "2.2"] -> [org.apache.maven.wagon/wagon-provider-api "2.2"] -> [org.codehaus.plexus/plexus-utils "3.0"]
 and
[leiningen-core "2.7.1"] -> [org.apache.maven.wagon/wagon-http "2.10"] -> [org.apache.maven.wagon/wagon-provider-api "2.10"] -> [org.codehaus.plexus/plexus-utils "3.0.15"]
 and
[leiningen-core "2.7.1"] -> [com.cemerick/pomegranate "0.3.1" :exclusions [org.tcrawley/dynapath]] -> [org.apache.maven.wagon/wagon-provider-api "2.2"] -> [org.codehaus.plexus/plexus-utils "3.0"]

Consider using these exclusions:
[leiningen-core "2.7.1" :exclusions [org.codehaus.plexus/plexus-utils]]

 [alembic "0.3.2"]
   [lein-as-resource "2.5.0" :exclusions [[org.clojure/clojure]]]
   [org.flatland/classlojure "0.7.0" :exclusions [[org.clojure/clojure]]]
   [org.tcrawley/dynapath "0.2.3" :exclusions [[org.clojure/clojure]]]
 [cheshire "5.8.0"]
   [com.fasterxml.jackson.core/jackson-core "2.9.0"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-cbor "2.9.0"]
   [com.fasterxml.jackson.dataformat/jackson-dataformat-smile "2.9.0"]
   [tigris "0.1.1"]
 [cider/cider-nrepl "0.14.0" :scope "provided"]
 [cider/orchard "0.3.0"]
 [cljs-tooling "0.2.0"]
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [com.cemerick/piggieback "0.2.2" :scope "test"]
 [commons-io "2.6" :scope "test"]
 [http-kit "2.2.0"]
 [lein-cljfmt "0.3.0"]
   [cljfmt "0.3.0"]
   [com.googlecode.java-diff-utils/diffutils "1.2.1"]
   [meta-merge "0.1.1"]
 [leiningen-core "2.7.1" :scope "test"]
   [bultitude "0.2.8" :scope "test" :exclusions [[org.tcrawley/dynapath]]]
   [classlojure "0.6.6" :scope "test"]
     [useful "0.8.3-alpha8" :scope "test"]
       [org.clojure/tools.macro "0.1.1" :scope "test"]
   [com.cemerick/pomegranate "0.3.1" :scope "test" :exclusions [[org.tcrawley/dynapath]]]
     [org.apache.maven.wagon/wagon-provider-api "2.2" :scope "test"]
     [org.apache.maven/maven-aether-provider "3.0.4" :scope "test"]
       [org.apache.maven/maven-model-builder "3.0.4" :scope "test"]
         [org.codehaus.plexus/plexus-interpolation "1.14" :scope "test"]
       [org.apache.maven/maven-model "3.0.4" :scope "test"]
       [org.apache.maven/maven-repository-metadata "3.0.4" :scope "test"]
       [org.codehaus.plexus/plexus-component-annotations "1.5.5" :scope "test" :exclusions [[junit]]]
       [org.codehaus.plexus/plexus-utils "2.0.6" :scope "test"]
     [org.sonatype.aether/aether-api "1.13.1" :scope "test"]
     [org.sonatype.aether/aether-connector-file "1.13.1" :scope "test"]
     [org.sonatype.aether/aether-connector-wagon "1.13.1" :scope "test" :exclusions [[org.codehaus.plexus/plexus-utils]]]
       [org.codehaus.plexus/plexus-classworlds "2.4" :scope "test"]
       [org.sonatype.sisu/sisu-inject-plexus "2.2.3" :scope "test"]
         [org.sonatype.sisu/sisu-inject-bean "2.2.3" :scope "test"]
           [org.sonatype.sisu/sisu-guice "3.0.3" :classifier "no_aop" :scope "test" :exclusions [[javax.inject] [aopalliance]]]
     [org.sonatype.aether/aether-impl "1.13.1" :scope "test"]
       [org.sonatype.aether/aether-spi "1.13.1" :scope "test"]
     [org.sonatype.aether/aether-util "1.13.1" :scope "test"]
   [com.hypirion/io "0.3.1" :scope "test"]
   [org.apache.maven.wagon/wagon-http "2.10" :scope "test"]
     [commons-logging "1.1.3" :scope "test"]
     [org.apache.httpcomponents/httpclient "4.3.5" :scope "test"]
       [commons-codec "1.6" :scope "test"]
     [org.apache.httpcomponents/httpcore "4.3.2" :scope "test"]
     [org.apache.maven.wagon/wagon-http-shared "2.10" :scope "test"]
       [commons-lang "2.6" :scope "test"]
       [org.jsoup/jsoup "1.7.2" :scope "test"]
   [pedantic "0.2.0" :scope "test"]
   [robert/hooke "1.3.0" :scope "test"]
 [me.raynes/fs "1.4.6"]
   [org.apache.commons/commons-compress "1.8"]
     [org.tukaani/xz "1.5"]
 [org.clojure/clojure "1.7.0" :scope "provided"]
 [org.clojure/clojurescript "1.9.89" :scope "test"]
   [com.google.javascript/closure-compiler "v20160315" :scope "test"]
     [args4j "2.0.26" :scope "test"]
     [com.google.code.findbugs/jsr305 "1.3.9" :scope "test"]
     [com.google.code.gson/gson "2.2.4" :scope "test"]
     [com.google.guava/guava "19.0" :scope "test"]
     [com.google.javascript/closure-compiler-externs "v20160315" :scope "test"]
     [com.google.protobuf/protobuf-java "2.5.0" :scope "test"]
   [org.clojure/data.json "0.2.6" :scope "test"]
   [org.clojure/google-closure-library "0.0-20160609-f42b4a24" :scope "test"]
     [org.clojure/google-closure-library-third-party "0.0-20160609-f42b4a24" :scope "test"]
   [org.mozilla/rhino "1.7R5" :scope "test"]
 [org.clojure/tools.analyzer.jvm "0.7.1"]
   [org.clojure/core.memoize "0.5.9"]
     [org.clojure/core.cache "0.6.5"]
       [org.clojure/data.priority-map "0.0.7"]
   [org.clojure/tools.analyzer "0.6.9"]
   [org.ow2.asm/asm-all "4.2"]
 [org.clojure/tools.namespace "0.3.0-alpha3"]
   [org.clojure/java.classpath "0.2.3"]
 [org.clojure/tools.nrepl "0.2.13"]
 [org.clojure/tools.reader "1.1.1"]
 [rewrite-clj "0.6.0"]
 [version-clj "0.1.2"]
```

**Comment by expez** [comment]
I updated `lein` from `2.7.x` to `2.8.1` and that solved the prefixing issue with mranderson.

However, now I get this:

```
$ lein repl
Java compiler not found; Be sure to use java from a JDK
rather than a JRE by modifying PATH or setting JAVA_CMD.
```

`lein` works as it should in other clojure projects.


Trying to force a JDK doesn't seem to affect this (I don't have JRE installed):

```
$which java                                                                                                                                    
/usr/bin/java

$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)

$ JAVA_CMD=/usr/bin/java lein test
Java compiler not found; Be sure to use java from a JDK
rather than a JRE by modifying PATH or setting JAVA_CMD.
```

Sorry about the slow response; I'm doing this in-between other tasks at work.  Thanks for your help @mgerlach-klick and @mbuczko it's greatly appreciated!

**Comment by bbatsov** [comment]
Maybe you should set your `JAVA_HOME` or whatever it was called? Also - is `javac` on your `PATH`?

**Comment by expez** [comment]
I re-installed the entire JDK.  For some reason javac wasn't included in the previous package I installed.

New snapshot is out.

**Comment by mgerlach-klick** [comment]
Weee! Thanks @expez

**Comment by benedekfazekas** [comment]
great work @expez, thanks!
