### ISSUE TITLE
Stack trace upon startup with jdk-13

### ISSUE THREAD

**Issue by slipset** [clojure-emacs/refactor-nrepl#287]
After upgrading all my packages, I now see the following stack-trace upon `cider-jack-in` with Leiningen:

```
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31) ~[netty-all-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:220) ~[netty-all-4.0.56.Final.jar:4.0.56.Final]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312) ~[na:na]
	at io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:214) ~[netty-all-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:203) ~[netty-all-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:74) ~[netty-all-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.buffer.UnpooledByteBufAllocator.<clinit>(UnpooledByteBufAllocator.java:37) ~[netty-all-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.buffer.ByteBufUtil.<clinit>(ByteBufUtil.java:70) ~[netty-all-4.0.56.Final.jar:4.0.56.Final]
	at io.netty.buffer.ByteBufAllocator.<clinit>(ByteBufAllocator.java:24) ~[netty-all-4.0.56.Final.jar:4.0.56.Final]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:416) ~[na:na]
	at clojure.lang.RT.classForName(RT.java:2211) ~[clojure-1.10.1.jar:na]
	at clojure.lang.RT.classForName(RT.java:2220) ~[clojure-1.10.1.jar:na]
	at refactor_nrepl.inlined_deps.toolsanalyzerjvm.v0v7v3.clojure.tools.analyzer.jvm.utils$maybe_class_from_string.invokeStatic(utils.clj:85) ~[na:na]
	At refactor_nrepl.inlined_deps.toolsanalyzerjvm.v0v7v3.clojure.tools.analyzer.jvm.utils$maybe_class_from_string.invoke(utils.clj:78) ~[na:na]
```

CIDER 0.25.0snapshot (package: 20200308.1030), nREPL 0.7.0-beta1
Clojure 1.10.1, Java 13.0.1

**Comment by bbatsov** [comment]
I'm assuming that's fixed by now, right?
