### ISSUE TITLE
Exception when invoking artifact-list first time

### ISSUE THREAD

**Issue by rundis** [clojure-emacs/refactor-nrepl#35]
I'm not 100% when this started, but it happens both in Snapshot-18 and 19.
When I start a new repl session (through Light Table that is) and then try to invoke the op artifact-list it croaks with this exception. 

Subsequent calls seems to work though.

```ERROR: Unhandled REPL handler exception processing message {:id c5792790-eac1-407c-99ca-849edf7bb4d5, :op artifact-list}
java.lang.NullPointerException
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:301)
	at refactor_nrepl.artifacts$stale_cache_QMARK_.invoke(artifacts.clj:36)
	at refactor_nrepl.artifacts$artifacts_list.invoke(artifacts.clj:89)
	at refactor_nrepl.artifacts$wrap_artifacts$fn__13260.invoke(artifacts.clj:122)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__414.invoke(middleware.clj:17)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:18)
	at clojure.tools.nrepl.server$handle$fn__769.invoke(server.clj:27)
	at clojure.core$binding_conveyor_fn$fn__4145.invoke(core.clj:1910)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)```

**Comment by expez** [comment]
Guessing there's a race condition here:

```clj
(defn- stale-cache? []
  (or (empty? @artifacts)
      (neg? (- millis-per-day
               (- (-> artifacts meta :last-modified .getTime)
                  (.getTime (java.util.Date.)))))))
```

`artifacts` isn't empty (because it's in the process of being filled) but the code updating the `:last-modified-metadata` hasn't run yet.

In `clj-refactor` we have an option to issue a dummy call which 'warms the cache' when the repl is first initialized so I've never hit this bug myself.  Thanks for the report!

**Comment by expez** [comment]
A new snapshot with this fix is now on clojars.
