### ISSUE TITLE
unhandled exception for configure

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/refactor-nrepl#56]
refactor-nrepl 1.0.2-SNAPSHOT
clj-refactor 20150406

```
ERROR: Unhandled REPL handler exception processing message {:op configure, :opts {:prefix-rewriting true}, :id 7}
java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'clojure.tools.nrepl.transport/Transport found for class: clojure.lang.Keyword
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:544)
	at clojure.tools.nrepl.transport$eval156$fn__157$G__145__164.invoke(transport.clj:16)
	at refactor_nrepl.middleware$config_reply.invoke(middleware.clj:66)
	at refactor_nrepl.middleware$wrap_refactor$fn__10499.invoke(middleware.clj:84)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
	at cider.nrepl.middleware.ns$wrap_ns$fn__2819.invoke(ns.clj:61)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
	at cider.nrepl.middleware.macroexpand$wrap_macroexpand$fn__2783.invoke(macroexpand.clj:79)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
	at cider.nrepl.middleware.info$wrap_info$fn__2573.invoke(info.clj:262)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
	at cider.nrepl.middleware.classpath$wrap_classpath$fn__1245.invoke(classpath.clj:25)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
	at cider.nrepl.middleware.apropos$wrap_apropos$fn__1178.invoke(apropos.clj:102)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
	at cider.nrepl.middleware.complete$wrap_complete$fn__2070.invoke(complete.clj:47)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
	at cider.nrepl.middleware.resource$wrap_resource$fn__2845.invoke(resource.clj:25)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
	at cider.nrepl.middleware.undef$wrap_undef$fn__3298.invoke(undef.clj:30)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__406.invoke(middleware.clj:17)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:19)
	at clojure.tools.nrepl.server$handle$fn__760.invoke(server.clj:28)
	at clojure.core$binding_conveyor_fn$fn__4145.invoke(core.clj:1910)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by benedekfazekas** [comment]
:+1:
